### PR TITLE
fix rescaling for FORD

### LINKED ISSUE #318: Unit mismatch for elementary reactions with arbitrary orders of reaction
Hi, 

I was looking at some mechanisms which have reactions with arbitrary reaction orders and found that the units of the pre-exponential coefficient in the Arrhenius rate reactions are not the same as those given by Cantera. I added a few print statements (after line 196 in `production.py`) to compare the units given by Cantera with those computed by PelePhysics, and ran a test for the 3 reaction chem-CH4-2step mechanism (all the reactions prescribe arbitrary reaction orders).

The output of the run is in this file: [ceptr_output.txt](https://github.com/AMReX-Combustion/PelePhysics/files/9425718/ceptr_output.txt). The units are significantly off.

The fix may be fairly easy though. Instead of using 
`ctuc = cu.prefactor_units(cc.ureg("kmol/m**3"), 1 - dim)` as in line 196 of `production.py`, we could extract the unit from Cantera as  `ctuc = cc.ureg(str(reaction.rate_coeff_units).split("at")[0][7:-2].replace("^", "**"))`. Of course there may be a simpler (or cleaner way) of doing this without having to do these string operations.

I did try to test the original and the fix for the homogeneous reactor test using CeptrTest, but, somehow, I was not able to get the PelePhysics simulation to work for either case. If I could get some pointers on how to create the homogeneous reactor test with PelePhysics, I'd be happy to attempt a fix for this issue.

Cheers!

### PR DESCRIPTION
**Pull request by malihass**
closes #318 #162 #23 

- [x] verify that no mech is changed (including QSS)
- [x] Compare all FORD mechs to cantera
- [x] Update mechs
- [x] Revert the safeguard against FORD

Co-authored-by: Anirudh Jonnalagadda <jonnalagadda.anirudh@gmail.com>
Co-authored-by: Samuel Whitman

### CODE REVIEW

**Comment by malihass** [comment]
FORD mech comparisons
FD is for finite difference Jacobian
AJ is for analytical Jacobian
Figure_1
Figure_2

**Review by marchdf — APPROVED** [review]

File: Support/Mechanism/Models/chem-CH4-2step/mechanism.H [hunk 1]
```diff
@@ -0,0 +1,2978 @@
...
+  // rate of progress
+  q = k_f * phi_f;
+  dqdT = dlnkfdT * k_f * phi_f;
+  // update wdot
+  wdot[0] -= 3 * q; // O2
+  wdot[1] += 4 * q; // H2O
+  wdot[2] -= 2 * q; // CH4
+  wdot[3] += 2 * q; // CO
+  // d()/d[O2]
+  dqdci = +k_f * 3.000000 * sc[0] * sc[0] * sc[2] * sc[2];
```
Comment (baperry2) [inline Support/Mechanism/Models/chem-CH4-2step/mechanism.H]: I think this still needs to be updated for the FORD stuff. This appears to have been calculated using the stoichiometric coefficients as reaction orders rather than using the FORD reaction orders.

Comment (malihass) [reply Support/Mechanism/Models/chem-CH4-2step/mechanism.H]: @baperry2 Good catch! I think I got all of it but I could use another pair of eyes to make sure I caught everything

**Review by baperry2 — APPROVED** [review]
Nice, looks good to me!

**Review by marchdf — APPROVED** [review]
